site_name: IntelliPen Documentation
site_url: https://intellipen.nrl.ai/
site_description: Your intelligent writing companion powered by Chrome's built-in AI
site_author: IntelliPen Team
repo_url: https://github.com/vietanhdev/IntelliPen
repo_name: vietanhdev/IntelliPen
edit_uri: edit/main/docs/

# Theme Configuration
theme:
  name: material
  logo: images/icon.svg
  favicon: images/icon32.png
  
  # Color Scheme - Material Blue
  palette:
    # Light mode
    - scheme: default
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    
    # Dark mode
    - scheme: slate
      primary: blue
      accent: light blue
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  # Features
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - navigation.expand
    - navigation.footer
    - navigation.indexes
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.path
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow
    - toc.integrate
  
  # Font
  font:
    text: Roboto
    code: Roboto Mono
  
  # Icon
  icon:
    repo: fontawesome/brands/github
    edit: material/pencil
    view: material/eye

# Plugins
plugins:
  - search:
      separator: '[\s\-,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - minify:
      minify_html: true
  - git-revision-date-localized:
      enable_creation_date: true
      type: timeago

# Extensions
markdown_extensions:
  # Python Markdown
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
      toc_depth: 3
  
  # Python Markdown Extensions
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde

# Extra CSS and JavaScript
extra_css:
  - stylesheets/extra.css

extra_javascript:
  - javascripts/extra.js

# Extra Configuration
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/vietanhdev/IntelliPen
      name: GitHub Repository
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/intellipen
      name: Follow us on Twitter
  
  analytics:
    feedback:
      title: Was this page helpful?
      ratings:
        - icon: material/emoticon-happy-outline
          name: This page was helpful
          data: 1
          note: >-
            Thanks for your feedback!
        - icon: material/emoticon-sad-outline
          name: This page could be improved
          data: 0
          note: >-
            Thanks for your feedback! Help us improve by
            <a href="https://github.com/vietanhdev/IntelliPen/issues/new" target="_blank" rel="noopener">opening an issue</a>.
  
  version:
    provider: mike

# Copyright
copyright: Copyright &copy; 2025 IntelliPen Team

# Navigation
nav:
  - Home: index.md
  - Getting Started: getting-started.md
  - User Guide: user-guide.md
  - Features:
    - Editor: features/editor.md
    - Translator: features/translator.md
    - Meeting Dashboard: features/meeting.md
  - Documentation:
    - Architecture: architecture.md
    - API Reference: api-reference.md
    - Design System: design-system.md
    - Theme System: theme-system.md
    - Testing: testing.md
  - Resources:
    - FAQ: faq.md
    - Privacy: privacy.md
    - Contributing: contributing.md
  - About: about.md
